[project]
name = "mikrotik-client-watcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.135.2",
    "pydantic",
    "jinja2>=3.1.2",
    "requests>=2.33.0",
    "librouteros>=4.0.0",
    "python-dotenv>=1.2.2"
    ]
